# Generated by Django 5.1.3 on 2024-12-03 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ruleta', '0005_alter_cliente_cedula_alter_cliente_numero_factura'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='telefono',
            field=models.CharField(blank=True, default=2, max_length=15),
            preserve_default=False,
        ),
    ]
