# Generated by Django 5.1.3 on 2024-12-03 06:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ruleta', '0008_remove_cliente_fecha_creacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cliente',
            name='numero_telefono',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
